[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "asciidoc-dita-toolkit"
version = "0.1.7"
description = "A toolkit for processing AsciiDoc files for DITA publishing workflows"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "Rolfe Dlugy-Hegwer", email = "rolfedh@users.noreply.github.com"}
]
keywords = ["asciidoc", "dita", "documentation", "publishing", "markup"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Documentation",
    "Topic :: Text Processing :: Markup",
]
dependencies = [
  # No external dependencies - uses only Python standard library
]

[project.urls]
Homepage = "https://github.com/rolfedh/asciidoc-dita-toolkit"
Repository = "https://github.com/rolfedh/asciidoc-dita-toolkit"
Issues = "https://github.com/rolfedh/asciidoc-dita-toolkit/issues"
Documentation = "https://github.com/rolfedh/asciidoc-dita-toolkit/blob/main/README.md"

[project.scripts]
asciidoc-dita-toolkit = "asciidoc_dita_toolkit.asciidoc_dita.toolkit:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["asciidoc_dita_toolkit*"]
