[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "asciidoc-dita-toolkit"
version = "1.0.0"
description = "A unified CLI toolkit for working with AsciiDoc and DITA."
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
  {name = "Rolfe Dlugy-Hegwer"}
]
dependencies = [
  # Add any required dependencies here
]

[project.urls]
Homepage = "https://github.com/yourusername/asciidoc-dita-toolkit"

[project.scripts]
asciidoc-dita = "asciidoc_dita.cli:main"

[tool.setuptools.packages.find]
where = ["asciidoc_dita_toolkit"]
