[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "asciidoc-dita-toolkit"
version = "1.0.0"
description = "A unified CLI toolkit for reviewing and fixing AsciiDoc content in DITA-based publishing workflows"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "Rolfe Dlugy-Hegwer", email = "rdlugyhe@example.com"}
]
keywords = ["asciidoc", "dita", "documentation", "technical-writing", "cli"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Documentation",
    "Topic :: Software Development :: Documentation",
    "Topic :: Text Processing :: Markup",
]
dependencies = [
  # No runtime dependencies currently - keeps it lightweight
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "pytest-cov>=2.0.0",
    "black>=22.0.0",
    "isort>=5.0.0",
    "flake8>=4.0.0",
    "build>=0.8.0",
    "twine>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/rdlugyhe/asciidoc-dita-toolkit"
Repository = "https://github.com/rdlugyhe/asciidoc-dita-toolkit"
Issues = "https://github.com/rdlugyhe/asciidoc-dita-toolkit/issues"
Documentation = "https://github.com/rdlugyhe/asciidoc-dita-toolkit#readme"

[project.scripts]
asciidoc-dita = "asciidoc_dita_toolkit.asciidoc_dita.cli:main"

[tool.setuptools.packages.find]
# Find packages from the project root
# This will find asciidoc_dita_toolkit and asciidoc_dita_toolkit.asciidoc_dita

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--strict-markers",
    "--strict-config",
    "--tb=short",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
]

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["asciidoc_dita_toolkit"]

[tool.coverage.run]
source = ["asciidoc_dita_toolkit"]
omit = [
    "*/tests/*",
    "*/test_*",
    "setup.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]
