[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adt-core"
version = "1.0.0"
description = "ADT Module Configuration and Sequencing System"
requires-python = ">=3.8"
dependencies = [
    "importlib-metadata>=1.0; python_version<'3.8'"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[project.entry-points."adt.modules"]
EntityReference = "modules.entity_reference:EntityReferenceModule"
ContentType = "modules.content_type:ContentTypeModule"
DirectoryConfig = "modules.directory_config:DirectoryConfigModule"

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov>=2.0",
    "black>=21.0",
    "flake8>=3.8",
]
