title: AsciiDoc DITA Toolkit
description: Documentation for technical writers preparing AsciiDoc content for DITA migration
baseurl: "/asciidoc-dita-toolkit"
url: "https://rolfedh.github.io"

# Modern theme - Just the Docs
remote_theme: just-the-docs/just-the-docs@v0.8.2
plugins:
  - jekyll-remote-theme

# Just the Docs theme configuration
color_scheme: light
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  heading_level: 2
  # Maximum amount of previews per search result
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  preview_words_after: 3
  # Set the search token separator
  tokenizer_separator: /[\s\-/]+/
  # Display the relative url in search results
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  button: false

# Logo and branding
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Footer configuration
footer_content: "Copyright &copy; 2025 AsciiDoc DITA Toolkit. Distributed under the MIT License."

# Social links (optional)
gh_edit_link: true
gh_edit_repository: "https://github.com/rolfedh/asciidoc-dita-toolkit"
gh_edit_branch: "main"
gh_edit_source: user-guide
gh_edit_view_mode: "tree"

# Navigation structure
nav_sort: case_insensitive

# Markdown configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
nav_links:
  - name: Home
    url: /
  - name: Plugins
    url: /plugins/
  - name: GitHub
    url: https://github.com/rolfedh/asciidoc-dita-toolkit

# Collections
collections:
  plugins:
    output: true
    permalink: /plugins/:name/

# Exclude from processing
exclude:
  - _README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include in processing
include:
  - _pages
