name: Daily Fetch Vale Fixtures

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:

jobs:
  fetch-fixtures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Make fetch-fixtures.sh executable
        run: chmod +x fetch-fixtures.sh

      - name: Run fetch-fixtures.sh
        run: ./fetch-fixtures.sh

      - name: Commit and push changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update test fixtures from asciidoctor-dita-vale"
          branch: auto/update-vale-fixtures
          title: "chore: update test fixtures from asciidoctor-dita-vale"
          body: |
            This PR updates the test fixtures from the upstream asciidoctor-dita-vale repository.
            Please review the changes to .expected files and fixtures.
          reviewers: |
            rolfedh
          delete-branch: true
